version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: amazoncorretto:8
    steps:
      - checkout
      - run: yum update && yum -y install curl
      - run: curl https://www.shiftleft.io/
workflows:
  workflow:
    jobs:
      - build
